version: '3'
services:
  coverage:
    build: .
    image: grpc-gcp-coverage
    volumes:
      - ./src:/grpc_gcp/src:delegated
      - ./out:/out:cached
    security_opt: 
      - seccomp:unconfined
